DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'metodo_pago_cdmx'
  ) THEN
    CREATE TYPE public.metodo_pago_cdmx AS ENUM ('efectivo_caja', 'transferencia');
  END IF;
END $$;

ALTER TABLE public.gastos_cdmx
  ADD COLUMN IF NOT EXISTS id_gasto_cdmx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS fecha_hora TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS descripcion TEXT,
  ADD COLUMN IF NOT EXISTS metodo_pago public.metodo_pago_cdmx NOT NULL DEFAULT 'efectivo_caja',
  ADD COLUMN IF NOT EXISTS id_cajero UUID;

ALTER TABLE public.gastos_cdmx
  ALTER COLUMN categoria TYPE TEXT
  USING categoria::TEXT;

ALTER TABLE public.gastos_cdmx
  ALTER COLUMN categoria SET DEFAULT 'otros';

UPDATE public.gastos_cdmx
SET
  fecha_hora = COALESCE(fecha_hora, fecha),
  descripcion = COALESCE(descripcion, concepto),
  id_cajero = COALESCE(id_cajero, usuario_id),
  categoria = CASE COALESCE(categoria, 'otros')
    WHEN 'papeleria' THEN 'papeleria'
    WHEN 'combustible' THEN 'transporte'
    WHEN 'viaticos' THEN 'alimentos'
    ELSE 'otros'
  END
WHERE
  fecha_hora IS NULL
  OR descripcion IS NULL
  OR id_cajero IS NULL
  OR categoria IN ('mantenimiento', 'viaticos', 'combustible', 'limpieza', 'papeleria', 'refacciones', 'servicios');

ALTER TABLE public.gastos_cdmx
  ALTER COLUMN fecha_hora SET NOT NULL,
  ALTER COLUMN descripcion SET NOT NULL,
  ALTER COLUMN categoria SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_gastos_cdmx_consecutivo ON public.gastos_cdmx(id_gasto_cdmx);
CREATE INDEX IF NOT EXISTS idx_gastos_cdmx_fecha_hora ON public.gastos_cdmx(fecha_hora DESC);
CREATE INDEX IF NOT EXISTS idx_gastos_cdmx_metodo_pago ON public.gastos_cdmx(metodo_pago);
CREATE INDEX IF NOT EXISTS idx_gastos_cdmx_id_cajero ON public.gastos_cdmx(id_cajero);

COMMENT ON COLUMN public.gastos_cdmx.id_gasto_cdmx IS 'Consecutivo operativo del gasto en Bodega CDMX';
COMMENT ON COLUMN public.gastos_cdmx.fecha_hora IS 'Momento exacto en que salio el dinero';
COMMENT ON COLUMN public.gastos_cdmx.descripcion IS 'Justificacion o descripcion del gasto';
COMMENT ON COLUMN public.gastos_cdmx.metodo_pago IS 'Metodo de pago del gasto local de CDMX';
COMMENT ON COLUMN public.gastos_cdmx.id_cajero IS 'Usuario autenticado que registro el gasto';
