// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function limpiar(valor: string | undefined): string | undefined {
  const recortado = valor?.trim();
  if (!recortado) return undefined;
  if (
    recortado.length >= 2 &&
    ((recortado.startsWith('"') && recortado.endsWith('"')) ||
      (recortado.startsWith("'") && recortado.endsWith("'")))
  ) {
    return recortado.slice(1, -1).trim() || undefined;
  }
  return recortado;
}

const SUPABASE_URL = limpiar(import.meta.env.VITE_SUPABASE_URL as string | undefined);
// Se acepta la anon key legacy como alternativa si el deploy aún no define la publishable key.
const SUPABASE_PUBLISHABLE_KEY =
  limpiar(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ??
  limpiar(import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined);

const variablesFaltantes = (
  [
    ["VITE_SUPABASE_URL", SUPABASE_URL],
    ["VITE_SUPABASE_PUBLISHABLE_KEY (o VITE_SUPABASE_ANON_KEY)", SUPABASE_PUBLISHABLE_KEY],
  ] as Array<[string, string | undefined]>
)
  .filter(([, valor]) => !valor)
  .map(([nombre]) => nombre);

if (variablesFaltantes.length > 0) {
  throw new Error(
    `Faltan variables de entorno de Supabase: ${variablesFaltantes.join(", ")}. ` +
      "Defínelas en .env para desarrollo local (y reinicia el servidor) o en el panel " +
      "de tu hosting para producción (Vercel → Settings → Environment Variables), " +
      "y reconstruye la app: las variables VITE_* se incluyen al compilar, no se " +
      "leen en tiempo de ejecución."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
